### ISSUE TITLE
Incorrect base URL in OpenAPI documentation produces incorrect production URLs

### ISSUE THREAD

**Issue by KrofDrakula** [forem/forem-docs#111]
### Explain the changes

The published API documentation has incorrect base URL set which makes the published OpenAPI documentation show the incorrect production API URLs for `dev.to`:

<img width="763" alt="image" src="https://github.com/forem/forem-docs/assets/112161/be8f9af0-a2ba-45c1-aa32-bd9406b6ca59">

All of the URLs should be prefixed with `https://dev.to`, not `https://dev.to/api`, which is why the generated URLs duplicate the `api/` part of the path and makes copy/pasting the URL incorrect.

### Suggested changes

Change the base URL for generating the published OpenAPI docs match the actual production URLs.

**Comment by AneeqaKhan** [comment]
Hello, I can work on this. Please assign it to me.

**Comment by AnthonyZhang220** [comment]
It's been a few months now. Do you have any updates on the issue? I could help to work on it as well.

**Comment by maestromac** [comment]
Resolved with https://github.com/forem/forem-docs/pull/124
