### ISSUE TITLE
References to `rtx` are out-of-date

### ISSUE THREAD

**Issue by medwards1771** [forem/forem-docs#127]
### Explain the changes

`rtx` is now `mise` ! per [this post](https://mise.jdx.dev/rtx.html) from the tool's maintainer, "The name was changed to avoid confusion with Nvidia's line of graphics cards. This wasn't a legal issue, but just general confusion."

### Suggested changes

update references to `rtx` with references to `mise`. (i plan create a PR for this)

### Additional context

i also plan to create a follow-up PR to rename the `.rtx.toml` file in [forem](https://github.com/forem/forem) to `.mise.toml` and update any config as needed per the instructions from https://mise.jdx.dev/rtx.html:

> mise will continue reading .rtx.toml files for some time but that eventually will be deprecated so please rename them to .mise.toml. mise will not read from RTX_* env vars so those will need to be changed to MISE_*. Anything using a local .rtx or .config/rtx directory will need to be moved to .mise/.config/mise.

**Comment by maestromac** [comment]
Resolved
