### ISSUE TITLE
Edit this page link isn't working

### ISSUE THREAD

**Issue by rhymes** [forem/forem-docs#3]
I opened https://forem-docs.netlify.app/docs/technical-overview/stack and clicked on "edit page" at the bottom, and it pointed to https://github.com/facebook/docusaurus/edit/master/website/docs/technical-overview/stack.md

I guess there's some configuration knob to change :D

**Comment by Zhao-Andy** [comment]
Fixed :D

**Comment by rhymes** [comment]
Awesome!!!
