### ISSUE TITLE
Labels linked inside the contributing guide "Where to contribute" section

### ISSUE THREAD

**Issue by dmarcoux** [forem/forem-docs#41]
### Explain the changes

In the [Where to contribute](https://developers.forem.com/contributing-guide/forem/#where-to-contribute) section of the contributing guide, there are links to issues labelled with `difficulty: easy`, `difficulty: medium` and `difficulty: hard`. Those labels do not exist, so they must have been deleted since this documentation has been written.

### Suggested changes

I suggest either deleting those links or replacing them with links to issues with the appropriate labels (I don't know which one...)

**Comment by FounderCasey** [comment]
Taken care of: https://github.com/forem/forem-docs/pull/73 - thanks @dmarcoux!
