### ISSUE TITLE
broken link from forem's readme

### ISSUE THREAD

**Issue by djuber** [forem/forem-docs#6]
Readme.md in forem/forem references the url https://developers.forem.com/installation/ as "View Full Installation Documentation", but this gives a 404 now.

The specific installation pages (child pages) are valid, for example https://developers.forem.com/installation/gitpod or https://developers.forem.com/installation/containers - but the "parent" directory doesn't exist.

I believe the gitdocs version may have had this as a directory, while the docosaurus site is either missing that placeholder (wasn't ported over) or doesn't support directory pages like this (the sidebar folder for installation is there and fine, but doesn't have a url to link to).

If this can be fixed on this end, not breaking a published link is the preferable solution. If not, I can move this issue to forem and we can link to specific pages within the installation group.

----

I'll just track the other items I find - looks like the contributors guide link moved from /contributing/ to /contributing-guide - linked PR 14587 changes the target in the docs - if we can preserve the public URL via a redirect that's preferable but if it's hard it's better to quickly fix the broken link.

**Comment by djuber** [comment]
@Zhao-Andy do you have any notion whether adding redirects or category pages is feasible or if it's better to just validate and fix all the text links in the forem (and possibly other) repos

I'm guessing the focus was on testing the in-app links (from admin, for example) and not text files like readme.md or contributing.md so these might have been missed. 

I'll take whatever approach you took with the app links (if you edited the targets in app when the paths changed, then that's what we'll do in forem)

**Comment by Zhao-Andy** [comment]
Ah lol just seeing this! I spent an hour spiking whether it was possible to make an index page for these broken links, but it's not that feasible. I'd rather just send the links to other places with my PR: https://github.com/forem/forem/pull/14588
