### ISSUE TITLE
Make headers in right side readable

### ISSUE THREAD

**Issue by tnir** [forem/forem-docs#60]
### Explain the changes

Make headers in right side readable (from black to white)

![developers forem com_api](https://user-images.githubusercontent.com/10229505/163066648-f6c71d78-6f35-40ce-a130-7276e7d3c8db.png)

### Suggested changes

Update redocusaurus from 0.4.4 to [0.5.1 or higher](https://github.com/rohit-gohri/redocusaurus/releases/tag/v0.5.1) to make headers in right side readable (from black to white).

### Additional context

- Origin of the issue: #5
- Fix in upstream: rohit-gohri/redocusaurus#112
- Why not to update to v1: https://redocusaurus.vercel.app/docs/guides/migrating-to-v1

**Comment by Zhao-Andy** [comment]
Hi @tnir, thanks for the issue! It makes sense to update to v1. Will take a look at the upgrade path some time.
