### ISSUE TITLE
`yarn install` needs to be run before `rails db:setup`

### ISSUE THREAD

**Issue by kenzo-tanaka** [forem/forem-docs#9]
Hi👋  
First of all thank you for the very helpful documentation!

When I cloned the [forem](https://github.com/forem/forem) locally and tried to start development, I encountered the following error.

```shell
$ rails db:setup
Database 'Forem_development' already exists
WARNING: sqlite and mysql triggers may not be shared by multiple actions
Seeding with multiplication factor: 1

  1. Creating Organizations.
  2. Creating 10 Users.
  User with email = admin@forem.local not found, proceeding...
rails aborted!
Sprockets::FileNotFound: couldn't find file 'honeybadger-js/dist/honeybadger.js' with type 'application/javascript'
Checked in these paths: 
```

I was able to solve the problem by running `yarn install`.

I think it would be more helpful to mention in the documentation that `yarn install` needs to be run before `rails db:setup`.
What do you think?

**Comment by maestromac** [comment]
Hey, @kenzo-tanaka 

Thanks for raising this issue. I agree that it should be specified that `yarn install` should happen before any db settings.

What's misleading here is that we have the "installation" section that would suggest running `bin/setup` instead. That would run all the necessary thing in the proper order.
